<?php
/**
 * Fired during plugin activation
 *
 * @link       https://github.com/marcoAspeitia31/
 * @since      1.0.0
 *
 * @package    Cideapps_Gp
 * @subpackage Cideapps_Gp/admin/custom-post-types
 */

/**
 * Fired during plugin activation.
 *
 * This class defines all code necessary to run during the plugin's activation.
 *
 * @since      1.0.0
 * @package    Cideapps_Gp
 * @subpackage Cideapps_Gp/admin/custom-post-types
 * @author     Marco Aspeitia <maspeitiap@devitm.com>
 */

class Cideapps_Gp_Teams_Post_Type {

    /**
     * This CPT was generated by GENERATE WP
     * 
     * @since   1.0.0
     * @link    https://generatewp.com/post-type/
     */
    // Register Custom Post Type
    // Register Custom Post Type
    function teams_post_type() {

        $labels = array(
            'name'                  => _x( 'Teams', 'Post Type General Name', 'cideapps-gp' ),
            'singular_name'         => _x( 'Team', 'Post Type Singular Name', 'cideapps-gp' ),
            'menu_name'             => __( 'Teams', 'cideapps-gp' ),
            'name_admin_bar'        => __( 'Team', 'cideapps-gp' ),
            'archives'              => __( 'Team Archives', 'cideapps-gp' ),
            'attributes'            => __( 'Team Attributes', 'cideapps-gp' ),
            'parent_item_colon'     => __( 'Parent Team:', 'cideapps-gp' ),
            'all_items'             => __( 'All Teams', 'cideapps-gp' ),
            'add_new_item'          => __( 'Add New Team', 'cideapps-gp' ),
            'add_new'               => __( 'Add New', 'cideapps-gp' ),
            'new_item'              => __( 'New Team', 'cideapps-gp' ),
            'edit_item'             => __( 'Edit Team', 'cideapps-gp' ),
            'update_item'           => __( 'Update Team', 'cideapps-gp' ),
            'view_item'             => __( 'View Team', 'cideapps-gp' ),
            'view_items'            => __( 'View Teams', 'cideapps-gp' ),
            'search_items'          => __( 'Search Team', 'cideapps-gp' ),
            'not_found'             => __( 'Not found', 'cideapps-gp' ),
            'not_found_in_trash'    => __( 'Not found in Trash', 'cideapps-gp' ),
            'featured_image'        => __( 'Featured Image', 'cideapps-gp' ),
            'set_featured_image'    => __( 'Set featured image', 'cideapps-gp' ),
            'remove_featured_image' => __( 'Remove featured image', 'cideapps-gp' ),
            'use_featured_image'    => __( 'Use as featured image', 'cideapps-gp' ),
            'insert_into_item'      => __( 'Insert into team', 'cideapps-gp' ),
            'uploaded_to_this_item' => __( 'Uploaded to this team', 'cideapps-gp' ),
            'items_list'            => __( 'Teams list', 'cideapps-gp' ),
            'items_list_navigation' => __( 'Teams list navigation', 'cideapps-gp' ),
            'filter_items_list'     => __( 'Filter teams list', 'cideapps-gp' ),
        );
        $args = array(
            'label'                 => __( 'Team', 'cideapps-gp' ),
            'description'           => __( 'Post Type Description', 'cideapps-gp' ),
            'labels'                => $labels,
            'supports'              => array( 'title', 'editor', 'thumbnail' ),
            'hierarchical'          => false,
            'public'                => true,
            'show_ui'               => true,
            'show_in_menu'          => true,
            'menu_position'         => 5,
            'menu_icon'             => 'dashicons-buddicons-buddypress-logo',
            'show_in_admin_bar'     => true,
            'show_in_nav_menus'     => true,
            'can_export'            => true,
            'has_archive'           => true,
            'exclude_from_search'   => false,
            'publicly_queryable'    => true,
            'capability_type'       => 'post',
            'show_in_rest'          => true,
        );
        register_post_type( 'teams', $args );

    }
    //add_action( 'init', 'teams_post_type', 0 );

}