<?php
/**
 * Fired during plugin activation
 *
 * @link       https://github.com/marcoAspeitia31/
 * @since      1.0.0
 *
 * @package    Cideapps_Gp
 * @subpackage Cideapps_Gp/admin/custom-post-types
 */

/**
 * Fired during plugin activation.
 *
 * This class defines all code necessary to run during the plugin's activation.
 *
 * @since      1.0.0
 * @package    Cideapps_Gp
 * @subpackage Cideapps_Gp/admin/custom-post-types
 * @author     Marco Aspeitia <maspeitiap@devitm.com>
 */

class Cideapps_Gp_Services_Post_Type {

    /**
     * This CPT was generated by GENERATE WP
     * 
     * @since   1.0.0
     * @link    https://generatewp.com/post-type/
     */
    function services_post_type() {
    
        $labels = array(
            'name'                  => _x( 'Services', 'Post Type General Name', 'cideapps-gp' ),
            'singular_name'         => _x( 'Service', 'Post Type Singular Name', 'cideapps-gp' ),
            'menu_name'             => __( 'Services', 'cideapps-gp' ),
            'name_admin_bar'        => __( 'Service', 'cideapps-gp' ),
            'archives'              => __( 'Service Archives', 'cideapps-gp' ),
            'attributes'            => __( 'Service Attributes', 'cideapps-gp' ),
            'parent_item_colon'     => __( 'Parent Service:', 'cideapps-gp' ),
            'all_items'             => __( 'All Services', 'cideapps-gp' ),
            'add_new_item'          => __( 'Add New Service', 'cideapps-gp' ),
            'add_new'               => __( 'Add New', 'cideapps-gp' ),
            'new_item'              => __( 'New Service', 'cideapps-gp' ),
            'edit_item'             => __( 'Edit Service', 'cideapps-gp' ),
            'update_item'           => __( 'Update Service', 'cideapps-gp' ),
            'view_item'             => __( 'View Service', 'cideapps-gp' ),
            'view_items'            => __( 'View Services', 'cideapps-gp' ),
            'search_items'          => __( 'Search Service', 'cideapps-gp' ),
            'not_found'             => __( 'Not found', 'cideapps-gp' ),
            'not_found_in_trash'    => __( 'Not found in Trash', 'cideapps-gp' ),
            'featured_image'        => __( 'Featured Image', 'cideapps-gp' ),
            'set_featured_image'    => __( 'Set featured image', 'cideapps-gp' ),
            'remove_featured_image' => __( 'Remove featured image', 'cideapps-gp' ),
            'use_featured_image'    => __( 'Use as featured image', 'cideapps-gp' ),
            'insert_into_item'      => __( 'Insert into item', 'cideapps-gp' ),
            'uploaded_to_this_item' => __( 'Uploaded to this item', 'cideapps-gp' ),
            'items_list'            => __( 'Services list', 'cideapps-gp' ),
            'items_list_navigation' => __( 'Services list navigation', 'cideapps-gp' ),
            'filter_items_list'     => __( 'Filter items list', 'cideapps-gp' ),
        );
        $args = array(
            'label'                 => __( 'Service', 'cideapps-gp' ),
            'description'           => __( 'Service Description', 'cideapps-gp' ),
            'labels'                => $labels,
            'supports'              => array( 'title', 'editor', 'thumbnail' ),
            'taxonomies'            => array( 'service_category' ),
            'hierarchical'          => false,
            'public'                => true,
            'show_ui'               => true,
            'show_in_menu'          => true,
            'menu_position'         => 5,
            'menu_icon'             => 'dashicons-awards',
            'show_in_admin_bar'     => true,
            'show_in_nav_menus'     => true,
            'can_export'            => true,
            'has_archive'           => true,
            'exclude_from_search'   => false,
            'publicly_queryable'    => true,
            'capability_type'       => 'page',
            'show_in_rest'          => true,
        );
        register_post_type( 'services', $args );
    
    }

}