<?php

class Cideapps_Gp_Taxonomies {

    /**
     * This Custom Taxonomy was generated by GENERATEWP
     * This taxonomy will be available only for services custom post type
     * 
     * @link https://generatewp.com/taxonomy/
     */
    function service_category() {

        $labels = array(
            'name'                       => _x( 'Service categories', 'Taxonomy General Name', 'cideapps-gp' ),
            'singular_name'              => _x( 'Service category', 'Taxonomy Singular Name', 'cideapps-gp' ),
            'menu_name'                  => __( 'Service category', 'cideapps-gp' ),
            'all_items'                  => __( 'All Service categories', 'cideapps-gp' ),
            'parent_item'                => __( 'Parent Service category', 'cideapps-gp' ),
            'parent_item_colon'          => __( 'Parent Service category:', 'cideapps-gp' ),
            'new_item_name'              => __( 'New Service category Name', 'cideapps-gp' ),
            'add_new_item'               => __( 'Add New Service category', 'cideapps-gp' ),
            'edit_item'                  => __( 'Edit Service category', 'cideapps-gp' ),
            'update_item'                => __( 'Update Service category', 'cideapps-gp' ),
            'view_item'                  => __( 'View Service category', 'cideapps-gp' ),
            'separate_items_with_commas' => __( 'Separate Service categories with commas', 'cideapps-gp' ),
            'add_or_remove_items'        => __( 'Add or remove Service category', 'cideapps-gp' ),
            'choose_from_most_used'      => __( 'Choose from the most used', 'cideapps-gp' ),
            'popular_items'              => __( 'Popular Service categories', 'cideapps-gp' ),
            'search_items'               => __( 'Search Service categories', 'cideapps-gp' ),
            'not_found'                  => __( 'Not Found', 'cideapps-gp' ),
            'no_terms'                   => __( 'No Service categories', 'cideapps-gp' ),
            'items_list'                 => __( 'Service categories list', 'cideapps-gp' ),
            'items_list_navigation'      => __( 'Service categories list navigation', 'cideapps-gp' ),
        );
        $rewrite = array(
            'slug'                       => 'service-category',
            'with_front'                 => true,
            'hierarchical'               => false,
        );
        $args = array(
            'labels'                     => $labels,
            'hierarchical'               => true,
            'public'                     => true,
            'show_ui'                    => true,
            'show_admin_column'          => true,
            'show_in_nav_menus'          => true,
            'show_tagcloud'              => true,
            'show_in_rest'               => true,
            'rewrite'                    => $rewrite,
        );
        register_taxonomy( 'service_category', array( 'services' ), $args );

    }

}